# SCREAPEANDO DATA NFL FANTASY 2011 A 2021

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

## STATS QB 2011 A 2021

In [70]:
request_2011_QB = pd.read_html("https://www.fantasypros.com/nfl/stats/qb.php?year=2011&scoring=PPR&range=full")
df_qb_2011 = request_2011_QB[0]
df_qb_2011.head()

  Unnamed: 0_level_0      Unnamed: 1_level_0 PASSING                        \
                Rank                  Player     CMP  ATT   PCT   YDS  Y/A
0                  1      Aaron Rodgers (GB)     343  502  68.3  4643  9.2
1                  2         Drew Brees (FA)     468  657  71.2  5476  8.3
2                  3        Cam Newton (CAR)     310  517  60.0  4051  7.8
3                  4          Tom Brady (TB)     401  611  65.6  5235  8.6
4                  5  Matthew Stafford (LAR)     421  663  63.5  5038  7.6

                RUSHING          MISC
   TD INT SACKS     ATT  YDS  TD   FL   G   FPTS FPTS/G   ROST
0  45   6    36      60  257   3    0  15  397.4   26.5  97.4%
1  46  14    24      21   86   1    1  16  387.8   24.2  35.7%
2  21  17    35     126  706  14    2  16  366.4   22.9  67.1%
3  39  12    32      43  109   3    2  16  366.4   22.9  99.0%
4  41  16    36      22   78   0    1  16  339.3   21.2  96.8%

In [316]:
## paso 1

df_qb_2011.columns = df_qb_2011.columns.map(''.join)

## paso 2 

columnas_qb = ['RANK','PLAYER','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_qb_2011.columns = columnas_qb

## paso 4

new_df_qb_2011 = pd.melt(df_qb_2011, id_vars = ['PLAYER'], value_vars = ['RANK', 'CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_qb_2011['year'] = '2011'

new_df_qb_2011['position'] = 'QB'

In [123]:
request_2012_QB = pd.read_html("https://www.fantasypros.com/nfl/stats/qb.php?year=2012&scoring=PPR&range=full")
df_qb_2012 = request_2012_QB[0]
df_qb_2012

In [318]:
## paso 1

df_qb_2012.columns = df_qb_2012.columns.map(''.join)

## paso 2 

columnas_qb = ['RANK','PLAYER','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_qb_2012.columns = columnas_qb

## paso 4

new_df_qb_2012 = pd.melt(df_qb_2012, id_vars = ['PLAYER'], value_vars = ['RANK', 'CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_qb_2012['year'] = '2012'

new_df_qb_2012['position'] = 'QB'

In [6]:
request_2013_QB = pd.read_html("https://www.fantasypros.com/nfl/stats/qb.php?year=2013&scoring=PPR&range=full")
df_qb_2013 = request_2013_QB[0]

In [320]:
## paso 1

df_qb_2013.columns = df_qb_2013.columns.map(''.join)

## paso 2 

columnas_qb = ['RANK','PLAYER','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_qb_2013.columns = columnas_qb

## paso 4

new_df_qb_2013 = pd.melt(df_qb_2013, id_vars = ['PLAYER'], value_vars = ['RANK', 'CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_qb_2013['year'] = '2013'

new_df_qb_2013['position'] = 'QB'

In [7]:
request_2014_QB = pd.read_html("https://www.fantasypros.com/nfl/stats/qb.php?year=2014&scoring=PPR&range=full")
df_qb_2014 = request_2014_QB[0]

In [321]:
## paso 1

df_qb_2014.columns = df_qb_2014.columns.map(''.join)

## paso 2 

columnas_qb = ['RANK','PLAYER','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_qb_2014.columns = columnas_qb

## paso 4

new_df_qb_2014 = pd.melt(df_qb_2014, id_vars = ['PLAYER'], value_vars = ['RANK', 'CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_qb_2014['year'] = '2014'

new_df_qb_2014['position'] = 'QB'

In [8]:
request_2015_QB = pd.read_html("https://www.fantasypros.com/nfl/stats/qb.php?year=2015&scoring=PPR&range=full")
df_qb_2015 = request_2015_QB[0]

In [322]:
## paso 1

df_qb_2015.columns = df_qb_2015.columns.map(''.join)

## paso 2 

columnas_qb = ['RANK','PLAYER','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_qb_2015.columns = columnas_qb

## paso 4

new_df_qb_2015 = pd.melt(df_qb_2015, id_vars = ['PLAYER'], value_vars = ['RANK', 'CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_qb_2015['year'] = '2015'

new_df_qb_2015['position'] = 'QB'

In [9]:
request_2016_QB = pd.read_html("https://www.fantasypros.com/nfl/stats/qb.php?year=2016&scoring=PPR&range=full")
df_qb_2016 = request_2016_QB[0]

In [323]:
## paso 1

df_qb_2016.columns = df_qb_2016.columns.map(''.join)

## paso 2 

columnas_qb = ['RANK','PLAYER','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_qb_2016.columns = columnas_qb

## paso 4

new_df_qb_2016 = pd.melt(df_qb_2016, id_vars = ['PLAYER'], value_vars = ['RANK','PLAYER','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_qb_2016['year'] = '2016'

new_df_qb_2016['position'] = 'QB'

In [10]:
request_2017_QB = pd.read_html("https://www.fantasypros.com/nfl/stats/qb.php?year=2017&scoring=PPR&range=full")
df_qb_2017 = request_2017_QB[0]

In [324]:
## paso 1

df_qb_2017.columns = df_qb_2017.columns.map(''.join)

## paso 2 

columnas_qb =  ['RANK','PLAYER','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_qb_2017.columns = columnas_qb

## paso 4

new_df_qb_2017 = pd.melt(df_qb_2017, id_vars = ['PLAYER'], value_vars = ['RANK','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_qb_2017['year'] = '2017'

new_df_qb_2017['position'] = 'QB'

In [11]:
request_2018_QB = pd.read_html("https://www.fantasypros.com/nfl/stats/qb.php?year=2018&scoring=PPR&range=full")
df_qb_2018 = request_2018_QB[0]

In [328]:
## paso 1

df_qb_2018.columns = df_qb_2018.columns.map(''.join)

## paso 2 

columnas_qb = ['RANK','PLAYER','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_qb_2018.columns = columnas_qb

## paso 4

new_df_qb_2018 = pd.melt(df_qb_2018, id_vars = ['PLAYER'], value_vars = ['RANK', 'CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_qb_2018['year'] = '2018'

new_df_qb_2018['position'] = 'QB'

In [12]:
request_2019_QB = pd.read_html("https://www.fantasypros.com/nfl/stats/qb.php?year=2019&scoring=PPR&range=full")
df_qb_2019 = request_2019_QB[0]

In [329]:
## paso 1

df_qb_2019.columns = df_qb_2019.columns.map(''.join)

## paso 2 

columnas_qb = ['RANK','PLAYER','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_qb_2019.columns = columnas_qb

## paso 4

new_df_qb_2019 = pd.melt(df_qb_2019, id_vars = ['PLAYER'], value_vars = ['RANK', 'CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_qb_2019['year'] = '2019'

new_df_qb_2019['position'] = 'QB'

In [144]:
request_2020_QB = pd.read_html("https://www.fantasypros.com/nfl/stats/qb.php?year=2020&scoring=PPR&range=full")
df_qb_2020 = request_2020_QB[0]

In [332]:
## paso 1

df_qb_2020.columns = df_qb_2020.columns.map(''.join)

## paso 2 

columnas_qb = ['RANK','PLAYER','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_qb_2020.columns = columnas_qb

## paso 4

new_df_qb_2020 = pd.melt(df_qb_2020, id_vars = ['PLAYER'], value_vars = ['RANK', 'CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_qb_2020['year'] = '2020'

new_df_qb_2020['position'] = 'QB'

In [146]:
request_2021_QB = pd.read_html("https://www.fantasypros.com/nfl/stats/qb.php?year=2021&scoring=PPR&range=full")
df_qb_2021 = request_2021_QB[0]

In [333]:
## paso 1

df_qb_2021.columns = df_qb_2021.columns.map(''.join)

## paso 2 

columnas_qb = ['RANK','PLAYER','CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_qb_2021.columns = columnas_qb

## paso 4

new_df_qb_2021 = pd.melt(df_qb_2021, id_vars = ['PLAYER'], value_vars = ['RANK', 'CMP_P','ATT_P','PCT_P', 'YDS_P', 'Y/A_P', 'TD_P', 'INT_P','SACKS_P',
                     'ATT_RU','YDS_RU','TD_RU','FL_M', 'G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_qb_2021['year'] = '2021'

new_df_qb_2021['position'] = 'QB'

In [334]:
stats_qb_2011_2021 = pd.concat([new_df_qb_2011, new_df_qb_2012, new_df_qb_2013, new_df_qb_2014, new_df_qb_2015, new_df_qb_2016, new_df_qb_2017, new_df_qb_2018, 
           new_df_qb_2019, new_df_qb_2020, new_df_qb_2021])

In [335]:
stats_qb_2011_2021.head()

                   PLAYER variable value  year position
0      Aaron Rodgers (GB)     RANK     1  2011       QB
1         Drew Brees (FA)     RANK     2  2011       QB
2        Cam Newton (CAR)     RANK     3  2011       QB
3          Tom Brady (TB)     RANK     4  2011       QB
4  Matthew Stafford (LAR)     RANK     5  2011       QB

## STATS RB 2011 A 2021

In [169]:
request_2011_RB = pd.read_html("https://www.fantasypros.com/nfl/stats/rb.php?year=2011&scoring=PPR&range=full")
df_RB_2011 = request_2011_RB[0]

In [181]:
## paso 1

df_RB_2011.columns = df_RB_2011.columns.map(''.join)

## paso 2 

columnas_RB = ['RANK','PLAYER','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_RB_2011.columns = columnas_RB

## paso 4

new_df_RB_2011 = pd.melt(df_RB_2011, id_vars = ['PLAYER'], value_vars = ['RANK','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_RB_2011['year'] = '2011'

new_df_RB_2011['position'] = 'RB'

In [16]:
request_2012_RB = pd.read_html("https://www.fantasypros.com/nfl/stats/rb.php?year=2012&scoring=PPR&range=full")
df_RB_2012 = request_2012_RB[0]

In [182]:
## paso 1

df_RB_2012.columns = df_RB_2012.columns.map(''.join)

## paso 2 

columnas_RB = ['RANK','PLAYER','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_RB_2012.columns = columnas_RB

## paso 4

new_df_RB_2012 = pd.melt(df_RB_2012, id_vars = ['PLAYER'], value_vars = ['RANK','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_RB_2012['year'] = '2012'

new_df_RB_2012['position'] = 'RB'

In [17]:
request_2013_RB = pd.read_html("https://www.fantasypros.com/nfl/stats/rb.php?year=2013&scoring=PPR&range=full")
df_RB_2013 = request_2013_RB[0]

In [183]:
## paso 1

df_RB_2013.columns = df_RB_2013.columns.map(''.join)

## paso 2 

columnas_RB = ['RANK','PLAYER','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_RB_2013.columns = columnas_RB

## paso 4

new_df_RB_2013 = pd.melt(df_RB_2013, id_vars = ['PLAYER'], value_vars = ['RANK','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_RB_2013['year'] = '2013'

new_df_RB_2013['position'] = 'RB'

In [18]:
request_2014_RB = pd.read_html("https://www.fantasypros.com/nfl/stats/rb.php?year=2014&scoring=PPR&range=full")
df_RB_2014 = request_2014_RB[0]

In [184]:
## paso 1

df_RB_2014.columns = df_RB_2014.columns.map(''.join)

## paso 2 

columnas_RB = ['RANK','PLAYER','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_RB_2014.columns = columnas_RB

## paso 4

new_df_RB_2014 = pd.melt(df_RB_2014, id_vars = ['PLAYER'], value_vars = ['RANK','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_RB_2014['year'] = '2014'

new_df_RB_2014['position'] = 'RB'

In [19]:
request_2015_RB = pd.read_html("https://www.fantasypros.com/nfl/stats/rb.php?year=2015&scoring=PPR&range=full")
df_RB_2015 = request_2015_RB[0]

In [189]:
## paso 1

df_RB_2015.columns = df_RB_2015.columns.map(''.join)

## paso 2 

columnas_RB = ['RANK','PLAYER','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_RB_2015.columns = columnas_RB

## paso 4

new_df_RB_2015 = pd.melt(df_RB_2015, id_vars = ['PLAYER'], value_vars = ['RANK','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_RB_2015['year'] = '2015'

new_df_RB_2015['position'] = 'RB'

In [20]:
request_2016_RB = pd.read_html("https://www.fantasypros.com/nfl/stats/rb.php?year=2016&scoring=PPR&range=full")
df_RB_2016 = request_2016_RB[0]

In [190]:
## paso 1

df_RB_2016.columns = df_RB_2016.columns.map(''.join)

## paso 2 

columnas_RB = ['RANK','PLAYER','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_RB_2016.columns = columnas_RB

## paso 4

new_df_RB_2016 = pd.melt(df_RB_2016, id_vars = ['PLAYER'], value_vars = ['RANK','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_RB_2016['year'] = '2016'

new_df_RB_2016['position'] = 'RB'

In [21]:
request_2017_RB = pd.read_html("https://www.fantasypros.com/nfl/stats/rb.php?year=2017&scoring=PPR&range=full")
df_RB_2017 = request_2017_RB[0]

In [191]:
## paso 1

df_RB_2017.columns = df_RB_2017.columns.map(''.join)

## paso 2 

columnas_RB = ['RANK','PLAYER','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_RB_2017.columns = columnas_RB

## paso 4

new_df_RB_2017 = pd.melt(df_RB_2017, id_vars = ['PLAYER'], value_vars = ['RANK','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_RB_2017['year'] = '2017'

new_df_RB_2017['position'] = 'RB'

In [22]:
request_2018_RB = pd.read_html("https://www.fantasypros.com/nfl/stats/rb.php?year=2018&scoring=PPR&range=full")
df_RB_2018 = request_2018_RB[0]

In [192]:
## paso 1

df_RB_2018.columns = df_RB_2018.columns.map(''.join)

## paso 2 

columnas_RB = ['RANK','PLAYER','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_RB_2018.columns = columnas_RB

## paso 4

new_df_RB_2018 = pd.melt(df_RB_2018, id_vars = ['PLAYER'], value_vars = ['RANK','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_RB_2018['year'] = '2018'

new_df_RB_2018['position'] = 'RB'

In [23]:
request_2019_RB = pd.read_html("https://www.fantasypros.com/nfl/stats/rb.php?year=2019&scoring=PPR&range=full")
df_RB_2019 = request_2019_RB[0]

In [194]:
## paso 1

df_RB_2019.columns = df_RB_2019.columns.map(''.join)

## paso 2 

columnas_RB = ['RANK','PLAYER','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_RB_2019.columns = columnas_RB

## paso 4

new_df_RB_2019 = pd.melt(df_RB_2019, id_vars = ['PLAYER'], value_vars = ['RANK','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_RB_2019['year'] = '2019'

new_df_RB_2019['position'] = 'RB'

In [24]:
request_2020_RB = pd.read_html("https://www.fantasypros.com/nfl/stats/rb.php?year=2020&scoring=PPR&range=full")
df_RB_2020 = request_2020_RB[0]

In [195]:
## paso 1

df_RB_2020.columns = df_RB_2020.columns.map(''.join)

## paso 2 

columnas_RB = ['RANK','PLAYER','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_RB_2020.columns = columnas_RB

## paso 4

new_df_RB_2020 = pd.melt(df_RB_2020, id_vars = ['PLAYER'], value_vars = ['RANK','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_RB_2020['year'] = '2020'

new_df_RB_2020['position'] = 'RB'

In [25]:
request_2021_RB = pd.read_html("https://www.fantasypros.com/nfl/stats/rb.php?year=2021&scoring=PPR&range=full")
df_RB_2021 = request_2021_RB[0]

In [196]:
## paso 1

df_RB_2021.columns = df_RB_2021.columns.map(''.join)

## paso 2 

columnas_RB = ['RANK','PLAYER','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_RB_2021.columns = columnas_RB

## paso 4

new_df_RB_2021 = pd.melt(df_RB_2021, id_vars = ['PLAYER'], value_vars = ['RANK','ATT_RU','YDS_RU', 'Y/A_RU', 'LG_RU', '20+_RU', 'TD_RU', 'REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'TD_RE',
                     'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_RB_2021['year'] = '2021'

new_df_RB_2021['position'] = 'RB'

In [200]:
stats_rb_2011_2021 = pd.concat([new_df_RB_2011, new_df_RB_2012, new_df_RB_2013, new_df_RB_2014, new_df_RB_2015, new_df_RB_2016, new_df_RB_2017, new_df_RB_2018, 
           new_df_RB_2019, new_df_RB_2020, new_df_RB_2021])

In [202]:
stats_rb_2011_2021.head()

                 PLAYER variable value  year position
0     LeSean McCoy (FA)     RANK     1  2011       RB
1  Adrian Peterson (FA)     RANK     2  2011       RB
2       Frank Gore (FA)     RANK     3  2011       RB
3   Mark Ingram II (NO)     RANK     4  2011       RB
4  Anthony Sherman (FA)     RANK     5  2011       RB

## STATS WR 2011 A 2021

In [26]:
request_2011_WR = pd.read_html("https://www.fantasypros.com/nfl/stats/wr.php?year=2011&scoring=PPR&range=full")
df_WR_2011 = request_2011_WR[0]

In [216]:
## paso 1

df_WR_2011.columns = df_WR_2011.columns.map(''.join)

## paso 2 

columnas_WR = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_WR_2011.columns = columnas_WR

## paso 4

new_df_WR_2011 = pd.melt(df_WR_2011, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_WR_2011['year'] = '2011'

new_df_WR_2011['position'] = 'WR'

In [27]:
request_2012_WR = pd.read_html("https://www.fantasypros.com/nfl/stats/wr.php?year=2012&scoring=PPR&range=full")
df_WR_2012 = request_2012_WR[0]

In [217]:
## paso 1

df_WR_2012.columns = df_WR_2012.columns.map(''.join)

## paso 2 

columnas_WR = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_WR_2012.columns = columnas_WR

## paso 4

new_df_WR_2012 = pd.melt(df_WR_2012, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_WR_2012['year'] = '2012'

new_df_WR_2012['position'] = 'WR'

In [28]:
request_2013_WR = pd.read_html("https://www.fantasypros.com/nfl/stats/wr.php?year=2013&scoring=PPR&range=full")
df_WR_2013 = request_2013_WR[0]

In [218]:
## paso 1

df_WR_2013.columns = df_WR_2013.columns.map(''.join)

## paso 2 

columnas_WR = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_WR_2013.columns = columnas_WR

## paso 4

new_df_WR_2013 = pd.melt(df_WR_2013, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_WR_2013['year'] = '2013'

new_df_WR_2013['position'] = 'WR'

In [29]:
request_2014_WR = pd.read_html("https://www.fantasypros.com/nfl/stats/wr.php?year=2014&scoring=PPR&range=full")
df_WR_2014 = request_2014_WR[0]

In [219]:
## paso 1

df_WR_2014.columns = df_WR_2014.columns.map(''.join)

## paso 2 

columnas_WR = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_WR_2014.columns = columnas_WR

## paso 4

new_df_WR_2014 = pd.melt(df_WR_2014, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_WR_2014['year'] = '2014'

new_df_WR_2014['position'] = 'WR'

In [30]:
request_2015_WR = pd.read_html("https://www.fantasypros.com/nfl/stats/wr.php?year=2015&scoring=PPR&range=full")
df_WR_2015 = request_2015_WR[0]

In [220]:
## paso 1

df_WR_2015.columns = df_WR_2015.columns.map(''.join)

## paso 2 

columnas_WR = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_WR_2015.columns = columnas_WR

## paso 4

new_df_WR_2015 = pd.melt(df_WR_2015, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_WR_2015['year'] = '2015'

new_df_WR_2015['position'] = 'WR'

In [31]:
request_2016_WR = pd.read_html("https://www.fantasypros.com/nfl/stats/wr.php?year=2016&scoring=PPR&range=full")
df_WR_2016 = request_2016_WR[0]

In [221]:
## paso 1

df_WR_2016.columns = df_WR_2016.columns.map(''.join)

## paso 2 

columnas_WR = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_WR_2016.columns = columnas_WR

## paso 4

new_df_WR_2016 = pd.melt(df_WR_2016, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_WR_2016['year'] = '2016'

new_df_WR_2016['position'] = 'WR'

In [32]:
request_2017_WR = pd.read_html("https://www.fantasypros.com/nfl/stats/wr.php?year=2017&scoring=PPR&range=full")
df_WR_2017 = request_2017_WR[0]

In [222]:
## paso 1

df_WR_2017.columns = df_WR_2017.columns.map(''.join)

## paso 2 

columnas_WR = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_WR_2017.columns = columnas_WR

## paso 4

new_df_WR_2017 = pd.melt(df_WR_2017, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_WR_2017['year'] = '2017'

new_df_WR_2017['position'] = 'WR'

In [33]:
request_2018_WR = pd.read_html("https://www.fantasypros.com/nfl/stats/wr.php?year=2018&scoring=PPR&range=full")
df_WR_2018 = request_2018_WR[0]

In [223]:
## paso 1

df_WR_2018.columns = df_WR_2018.columns.map(''.join)

## paso 2 

columnas_WR = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_WR_2018.columns = columnas_WR

## paso 4

new_df_WR_2018 = pd.melt(df_WR_2018, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_WR_2018['year'] = '2018'

new_df_WR_2018['position'] = 'WR'

In [34]:
request_2019_WR = pd.read_html("https://www.fantasypros.com/nfl/stats/wr.php?year=2019&scoring=PPR&range=full")
df_WR_2019 = request_2019_WR[0]

In [232]:
## paso 1

df_WR_2019.columns = df_WR_2019.columns.map(''.join)

## paso 2 

columnas_WR = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_WR_2019.columns = columnas_WR

## paso 4

new_df_WR_2019 = pd.melt(df_WR_2019, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_WR_2019['year'] = '2019'

new_df_WR_2019['position'] = 'WR'

In [233]:
request_2020_WR = pd.read_html("https://www.fantasypros.com/nfl/stats/wr.php?year=2020&scoring=PPR&range=full")
df_WR_2020 = request_2020_WR[0]

In [234]:
## paso 1

df_WR_2020.columns = df_WR_2020.columns.map(''.join)

## paso 2 

columnas_WR = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_WR_2020.columns = columnas_WR

## paso 4

new_df_WR_2020 = pd.melt(df_WR_2020, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_WR_2020['year'] = '2019'

new_df_WR_2020['position'] = 'WR'

In [235]:
request_2021_WR = pd.read_html("https://www.fantasypros.com/nfl/stats/wr.php?year=2021&scoring=PPR&range=full")
df_WR_2021 = request_2021_WR[0]

In [236]:
## paso 1

df_WR_2021.columns = df_WR_2021.columns.map(''.join)

## paso 2 

columnas_WR = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_WR_2021.columns = columnas_WR

## paso 4

new_df_WR_2021 = pd.melt(df_WR_2011, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_WR_2021['year'] = '2021'

new_df_WR_2021['position'] = 'WR'

In [253]:
stats_WR_2011_2021 = pd.concat([new_df_WR_2011, new_df_WR_2012, new_df_WR_2013, new_df_WR_2014, new_df_WR_2015, new_df_WR_2016, new_df_WR_2017, new_df_WR_2018, 
           new_df_WR_2019, new_df_WR_2020, new_df_WR_2021])

In [254]:
stats_WR_2011_2021.head()

                  PLAYER variable value  year position
0  Larry Fitzgerald (FA)     RANK     1  2011       WR
1       A.J. Green (ARI)     RANK     2  2011       WR
2        Dez Bryant (FA)     RANK     3  2011       WR
3      Julio Jones (TEN)     RANK     4  2011       WR
4     Antonio Brown (TB)     RANK     5  2011       WR

## STATS TE 2011 A 2021

In [37]:
request_2011_TE = pd.read_html("https://www.fantasypros.com/nfl/stats/te.php?year=2011&scoring=PPR&range=full")
df_TE_2011 = request_2011_TE[0]

In [241]:
## paso 1

df_TE_2011.columns = df_TE_2011.columns.map(''.join)

## paso 2 

columnas_TE = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_TE_2011.columns = columnas_TE

## paso 4

new_df_TE_2011 = pd.melt(df_TE_2011, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_TE_2011['year'] = '2011'

new_df_TE_2011['position'] = 'TE'

In [242]:
request_2012_TE = pd.read_html("https://www.fantasypros.com/nfl/stats/te.php?year=2012&scoring=PPR&range=full")
df_TE_2012 = request_2012_TE[0]

In [243]:
## paso 1

df_TE_2012.columns = df_TE_2012.columns.map(''.join)

## paso 2 

columnas_TE = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_TE_2012.columns = columnas_TE

## paso 4

new_df_TE_2012 = pd.melt(df_TE_2012, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_TE_2012['year'] = '2012'

new_df_TE_2012['position'] = 'TE'

In [39]:
request_2013_TE = pd.read_html("https://www.fantasypros.com/nfl/stats/te.php?year=2013&scoring=PPR&range=full")
df_TE_2013 = request_2013_TE[0]

In [244]:
## paso 1

df_TE_2013.columns = df_TE_2013.columns.map(''.join)

## paso 2 

columnas_TE = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_TE_2013.columns = columnas_TE

## paso 4

new_df_TE_2013 = pd.melt(df_TE_2013, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_TE_2013['year'] = '2013'

new_df_TE_2013['position'] = 'TE'

In [40]:
request_2014_TE = pd.read_html("https://www.fantasypros.com/nfl/stats/te.php?year=2014&scoring=PPR&range=full")
df_TE_2014 = request_2014_TE[0]

In [245]:
## paso 1

df_TE_2014.columns = df_TE_2014.columns.map(''.join)

## paso 2 

columnas_TE = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_TE_2014.columns = columnas_TE

## paso 4

new_df_TE_2014 = pd.melt(df_TE_2014, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_TE_2014['year'] = '2014'

new_df_TE_2014['position'] = 'TE'

In [41]:
request_2015_TE = pd.read_html("https://www.fantasypros.com/nfl/stats/te.php?year=2015&scoring=PPR&range=full")
df_TE_2015 = request_2015_TE[0]

In [246]:
## paso 1

df_TE_2015.columns = df_TE_2015.columns.map(''.join)

## paso 2 

columnas_TE = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_TE_2015.columns = columnas_TE

## paso 4

new_df_TE_2015 = pd.melt(df_TE_2015, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_TE_2015['year'] = '2015'

new_df_TE_2015['position'] = 'TE'

In [42]:
request_2016_TE = pd.read_html("https://www.fantasypros.com/nfl/stats/te.php?year=2016&scoring=PPR&range=full")
df_TE_2016 = request_2016_TE[0]

In [247]:
## paso 1

df_TE_2016.columns = df_TE_2016.columns.map(''.join)

## paso 2 

columnas_TE = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_TE_2016.columns = columnas_TE

## paso 4

new_df_TE_2016 = pd.melt(df_TE_2016, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_TE_2016['year'] = '2016'

new_df_TE_2016['position'] = 'TE'

In [43]:
request_2017_TE = pd.read_html("https://www.fantasypros.com/nfl/stats/te.php?year=2017&scoring=PPR&range=full")
df_TE_2017 = request_2017_TE[0]

In [248]:
## paso 1

df_TE_2017.columns = df_TE_2017.columns.map(''.join)

## paso 2 

columnas_TE = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_TE_2017.columns = columnas_TE

## paso 4

new_df_TE_2017 = pd.melt(df_TE_2017, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_TE_2017['year'] = '2017'

new_df_TE_2017['position'] = 'TE'

In [44]:
request_2018_TE = pd.read_html("https://www.fantasypros.com/nfl/stats/te.php?year=2018&scoring=PPR&range=full")
df_TE_2018 = request_2018_TE[0]

In [249]:
## paso 1

df_TE_2018.columns = df_TE_2018.columns.map(''.join)

## paso 2 

columnas_TE = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_TE_2018.columns = columnas_TE

## paso 4

new_df_TE_2018 = pd.melt(df_TE_2018, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_TE_2018['year'] = '2018'

new_df_TE_2018['position'] = 'TE'

In [45]:
request_2019_TE = pd.read_html("https://www.fantasypros.com/nfl/stats/te.php?year=2019&scoring=PPR&range=full")
df_TE_2019 = request_2019_TE[0]

In [250]:
## paso 1

df_TE_2019.columns = df_TE_2019.columns.map(''.join)

## paso 2 

columnas_TE = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_TE_2019.columns = columnas_TE

## paso 4

new_df_TE_2019 = pd.melt(df_TE_2019, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_TE_2019['year'] = '2019'

new_df_TE_2019['position'] = 'TE'

In [46]:
request_2020_TE = pd.read_html("https://www.fantasypros.com/nfl/stats/te.php?year=2020&scoring=PPR&range=full")
df_TE_2020 = request_2020_TE[0]

In [251]:
## paso 1

df_TE_2020.columns = df_TE_2020.columns.map(''.join)

## paso 2 

columnas_TE = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_TE_2020.columns = columnas_TE

## paso 4

new_df_TE_2020 = pd.melt(df_TE_2020, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_TE_2020['year'] = '2020'

new_df_TE_2020['position'] = 'TE'

In [47]:
request_2021_TE = pd.read_html("https://www.fantasypros.com/nfl/stats/te.php?year=2021&scoring=PPR&range=full")
df_TE_2021 = request_2021_TE[0]

In [252]:
## paso 1

df_TE_2021.columns = df_TE_2021.columns.map(''.join)

## paso 2 

columnas_TE = ['RANK','PLAYER','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU', 'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 3

df_TE_2021.columns = columnas_TE

## paso 4

new_df_TE_2021 = pd.melt(df_TE_2021, id_vars = ['PLAYER'], value_vars = ['RANK','REC_RE', 'TGT_RE','YDS_RE', 'Y/R_RE', 'LG_RE', '20+_RE', 'TD_RE', 'ATT_RU','YDS_RU', 'TD_RU',
                                                                         'FL_M','G_M','FPTS_M', 'FPTS/G_M', 'ROST_M'])
new_df_TE_2021['year'] = '2021'

new_df_TE_2021['position'] = 'TE'

In [255]:
stats_TE_2011_2021 = pd.concat([new_df_TE_2011, new_df_TE_2012, new_df_TE_2013, new_df_TE_2014, new_df_TE_2015, new_df_TE_2016, new_df_TE_2017, new_df_TE_2018, 
           new_df_TE_2019, new_df_TE_2020, new_df_TE_2021])

In [256]:
stats_TE_2011_2021.head()

                PLAYER variable value  year position
0  Rob Gronkowski (TB)     RANK     1  2011       TE
1   Jimmy Graham (CHI)     RANK     2  2011       TE
2    Jason Witten (FA)     RANK     3  2011       TE
3     Jared Cook (LAC)     RANK     4  2011       TE
4      Greg Olsen (FA)     RANK     5  2011       TE

## STATS PATEADORES 2011 A 2021

In [258]:
request_2011_K = pd.read_html("https://www.fantasypros.com/nfl/stats/k.php?year=2011&scoring=PPR&range=full")
df_K_2011 = request_2011_K[0]

In [265]:
## paso 1 

columnas_K = ['RANK', 'PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_K_2011.columns = columnas_K

## paso 3

new_df_K_2011 = pd.melt(df_K_2011, id_vars = ['PLAYER'], value_vars = ['RANK','PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_K_2011['year'] = '2011'

new_df_K_2011['position'] = 'K'

In [49]:
request_2012_K = pd.read_html("https://www.fantasypros.com/nfl/stats/k.php?year=2012&scoring=PPR&range=full")
df_K_2012 = request_2012_K[0]

In [271]:
## paso 1 

columnas_K = ['RANK', 'PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_K_2012.columns = columnas_K

## paso 3

new_df_K_2012 = pd.melt(df_K_2012, id_vars = ['PLAYER'], value_vars = ['RANK','PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_K_2012['year'] = '2012'

new_df_K_2012['position'] = 'K'

In [272]:
request_2013_K = pd.read_html("https://www.fantasypros.com/nfl/stats/k.php?year=2013&scoring=PPR&range=full")
df_K_2013 = request_2013_K[0]

In [273]:
## paso 1 

columnas_K = ['RANK', 'PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_K_2013.columns = columnas_K

## paso 3

new_df_K_2013 = pd.melt(df_K_2013, id_vars = ['PLAYER'], value_vars = ['RANK','PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_K_2013['year'] = '2012'

new_df_K_2013['position'] = 'K'

In [274]:
request_2014_K = pd.read_html("https://www.fantasypros.com/nfl/stats/k.php?year=2014&scoring=PPR&range=full")
df_K_2014 = request_2014_K[0]

In [275]:
## paso 1 

columnas_K = ['RANK', 'PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_K_2014.columns = columnas_K

## paso 3

new_df_K_2014 = pd.melt(df_K_2014, id_vars = ['PLAYER'], value_vars = ['RANK','PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_K_2014['year'] = '2014'

new_df_K_2014['position'] = 'K'

In [52]:
request_2015_K = pd.read_html("https://www.fantasypros.com/nfl/stats/k.php?year=2015&scoring=PPR&range=full")
df_K_2015 = request_2015_K[0]

In [276]:
## paso 1 

columnas_K = ['RANK', 'PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_K_2015.columns = columnas_K

## paso 3

new_df_K_2015 = pd.melt(df_K_2015, id_vars = ['PLAYER'], value_vars = ['RANK','PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_K_2015['year'] = '2015'

new_df_K_2015['position'] = 'K'

In [53]:
request_2016_K = pd.read_html("https://www.fantasypros.com/nfl/stats/k.php?year=2016&scoring=PPR&range=full")
df_K_2016 = request_2016_K[0]

In [277]:
## paso 1 

columnas_K = ['RANK', 'PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_K_2016.columns = columnas_K

## paso 3

new_df_K_2016 = pd.melt(df_K_2016, id_vars = ['PLAYER'], value_vars = ['RANK','PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_K_2016['year'] = '2016'

new_df_K_2016['position'] = 'K'

In [54]:
request_2017_K = pd.read_html("https://www.fantasypros.com/nfl/stats/k.php?year=2017&scoring=PPR&range=full")
df_K_2017 = request_2017_K[0]

In [278]:
## paso 1 

columnas_K = ['RANK', 'PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_K_2017.columns = columnas_K

## paso 3

new_df_K_2017 = pd.melt(df_K_2017, id_vars = ['PLAYER'], value_vars = ['RANK','PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_K_2017['year'] = '2017'

new_df_K_2017['position'] = 'K'

In [55]:
request_2018_K = pd.read_html("https://www.fantasypros.com/nfl/stats/k.php?year=2018&scoring=PPR&range=full")
df_K_2018 = request_2018_K[0]

In [287]:
## paso 1 

columnas_K = ['RANK', 'PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_K_2018.columns = columnas_K

## paso 3

new_df_K_2018 = pd.melt(df_K_2018, id_vars = ['PLAYER'], value_vars = ['RANK','PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_K_2018['year'] = '2018'

new_df_K_2018['position'] = 'K'

In [282]:
request_2019_K = pd.read_html("https://www.fantasypros.com/nfl/stats/k.php?year=2019&scoring=PPR&range=full")
df_K_2019 = request_2019_K[0]

In [288]:
## paso 1 

columnas_K = ['RANK', 'PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_K_2019.columns = columnas_K

## paso 3

new_df_K_2019 = pd.melt(df_K_2019, id_vars = ['PLAYER'], value_vars = ['RANK','PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_K_2019['year'] = '2019'

new_df_K_2019['position'] = 'K'

In [284]:
request_2020_K = pd.read_html("https://www.fantasypros.com/nfl/stats/k.php?year=2020&scoring=PPR&range=full")
df_K_2020 = request_2020_K[0]

In [289]:
## paso 1 

columnas_K = ['RANK', 'PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_K_2020.columns = columnas_K

## paso 3

new_df_K_2020 = pd.melt(df_K_2020, id_vars = ['PLAYER'], value_vars = ['RANK','PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_K_2020['year'] = '2020'

new_df_K_2020['position'] = 'K'

In [58]:
request_2021_K = pd.read_html("https://www.fantasypros.com/nfl/stats/k.php?year=2021&scoring=PPR&range=full")
df_K_2021 = request_2021_K[0]

In [290]:
## paso 1 

columnas_K = ['RANK', 'PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_K_2021.columns = columnas_K

## paso 3

new_df_K_2021 = pd.melt(df_K_2020, id_vars = ['PLAYER'], value_vars = ['RANK','PLAYER', 'FG_PA', 'FGA_PA', 'PCT_PA', 'LG_PA', '1-19_PA', '20-29_PA', '30-39_PA',
       '40-49_PA', '50+_PA', 'XPT_PA', 'XPA_PA', 'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_K_2021['year'] = '2021'

new_df_K_2021['position'] = 'K'

In [291]:
stats_K_2011_2021 = pd.concat([new_df_K_2011, new_df_K_2012, new_df_K_2013, new_df_K_2014, new_df_K_2015, new_df_K_2016, new_df_K_2017, new_df_K_2018, 
           new_df_K_2019, new_df_K_2020, new_df_K_2021])

In [292]:
stats_K_2011_2021.head()

                    PLAYER variable value  year position
0         Mike Nugent (FA)     RANK     1  2011        K
1          Dan Bailey (FA)     RANK     2  2011        K
2        Graham Gano (NYG)     RANK     3  2011        K
3        Robbie Gould (SF)     RANK     4  2011        K
4  Stephen Gostkowski (FA)     RANK     5  2011        K

## STATS DEFENSAS 2011 A 2021

In [59]:
request_2011_DST = pd.read_html("https://www.fantasypros.com/nfl/stats/dst.php?year=2011&scoring=PPR&range=full")
df_DST_2011 = request_2011_DST[0]

In [298]:
## paso 1 

columnas_DST = ['RANK', 'PLAYER', 'SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_DST_2011.columns = columnas_DST

## paso 3

new_df_DST_2011 = pd.melt(df_DST_2011, id_vars = ['PLAYER'], value_vars = ['RANK','SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_DST_2011['year'] = '2011'

new_df_DST_2011['position'] = 'DST'

In [60]:
request_2012_DST = pd.read_html("https://www.fantasypros.com/nfl/stats/dst.php?year=2012&scoring=PPR&range=full")
df_DST_2012 = request_2012_DST[0]

In [299]:
## paso 1 

columnas_DST = ['RANK', 'PLAYER', 'SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_DST_2012.columns = columnas_DST

## paso 3

new_df_DST_2012 = pd.melt(df_DST_2012, id_vars = ['PLAYER'], value_vars = ['RANK','SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_DST_2012['year'] = '2012'

new_df_DST_2012['position'] = 'DST'

In [61]:
request_2013_DST = pd.read_html("https://www.fantasypros.com/nfl/stats/dst.php?year=2013&scoring=PPR&range=full")
df_DST_2013 = request_2013_DST[0]

In [300]:
## paso 1 

columnas_DST = ['RANK', 'PLAYER', 'SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_DST_2013.columns = columnas_DST

## paso 3

new_df_DST_2013 = pd.melt(df_DST_2013, id_vars = ['PLAYER'], value_vars = ['RANK','SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_DST_2013['year'] = '2013'

new_df_DST_2013['position'] = 'DST'

In [62]:
request_2014_DST = pd.read_html("https://www.fantasypros.com/nfl/stats/dst.php?year=2014&scoring=PPR&range=full")
df_DST_2014 = request_2014_DST[0]

In [304]:
## paso 1 

columnas_DST = ['RANK', 'PLAYER', 'SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_DST_2014.columns = columnas_DST

## paso 3

new_df_DST_2014 = pd.melt(df_DST_2014, id_vars = ['PLAYER'], value_vars = ['RANK','SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_DST_2014['year'] = '2014'

new_df_DST_2014['position'] = 'DST'

In [63]:
request_2015_DST = pd.read_html("https://www.fantasypros.com/nfl/stats/dst.php?year=2015&scoring=PPR&range=full")
df_DST_2015 = request_2015_DST[0]

In [305]:
## paso 1 

columnas_DST = ['RANK', 'PLAYER', 'SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_DST_2015.columns = columnas_DST

## paso 3

new_df_DST_2015 = pd.melt(df_DST_2015, id_vars = ['PLAYER'], value_vars = ['RANK','SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_DST_2015['year'] = '2015'

new_df_DST_2015['position'] = 'DST'

In [64]:
request_2016_DST = pd.read_html("https://www.fantasypros.com/nfl/stats/dst.php?year=2016&scoring=PPR&range=full")
df_DST_2016 = request_2016_DST[0]

In [303]:
## paso 1 

columnas_DST = ['RANK', 'PLAYER', 'SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_DST_2016.columns = columnas_DST

## paso 3

new_df_DST_2016 = pd.melt(df_DST_2016, id_vars = ['PLAYER'], value_vars = ['RANK','SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_DST_2016['year'] = '2016'

new_df_DST_2016['position'] = 'DST'

In [65]:
request_2017_DST = pd.read_html("https://www.fantasypros.com/nfl/stats/dst.php?year=2017&scoring=PPR&range=full")
df_DST_2017 = request_2017_DST[0]

In [306]:
## paso 1 

columnas_DST = ['RANK', 'PLAYER', 'SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_DST_2017.columns = columnas_DST

## paso 3

new_df_DST_2017 = pd.melt(df_DST_2017, id_vars = ['PLAYER'], value_vars = ['RANK','SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_DST_2017['year'] = '2017'

new_df_DST_2017['position'] = 'DST'

In [66]:
request_2018_DST = pd.read_html("https://www.fantasypros.com/nfl/stats/dst.php?year=2018&scoring=PPR&range=full")
df_DST_2018 = request_2018_DST[0]

In [307]:
## paso 1 

columnas_DST = ['RANK', 'PLAYER', 'SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_DST_2018.columns = columnas_DST

## paso 3

new_df_DST_2018 = pd.melt(df_DST_2018, id_vars = ['PLAYER'], value_vars = ['RANK','SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_DST_2018['year'] = '2018'

new_df_DST_2018['position'] = 'DST'

In [67]:
request_2019_DST = pd.read_html("https://www.fantasypros.com/nfl/stats/dst.php?year=2019&scoring=PPR&range=full")
df_DST_2019 = request_2019_DST[0]

In [308]:
## paso 1 

columnas_DST = ['RANK', 'PLAYER', 'SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_DST_2019.columns = columnas_DST

## paso 3

new_df_DST_2019 = pd.melt(df_DST_2019, id_vars = ['PLAYER'], value_vars = ['RANK','SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_DST_2019['year'] = '2019'

new_df_DST_2019['position'] = 'DST'

In [68]:
request_2020_DST = pd.read_html("https://www.fantasypros.com/nfl/stats/dst.php?year=2020&scoring=PPR&range=full")
df_DST_2020 = request_2020_DST[0]

In [309]:
## paso 1 

columnas_DST = ['RANK', 'PLAYER', 'SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_DST_2020.columns = columnas_DST

## paso 3

new_df_DST_2020 = pd.melt(df_DST_2020, id_vars = ['PLAYER'], value_vars = ['RANK','SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_DST_2020['year'] = '2020'

new_df_DST_2020['position'] = 'DST'

In [69]:
request_2021_DST = pd.read_html("https://www.fantasypros.com/nfl/stats/dst.php?year=2021&scoring=PPR&range=full")
df_DST_2021 = request_2021_DST[0]

In [310]:
## paso 1 

columnas_DST = ['RANK', 'PLAYER', 'SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M']

## paso 2

df_DST_2021.columns = columnas_DST

## paso 3

new_df_DST_2021 = pd.melt(df_DST_2021, id_vars = ['PLAYER'], value_vars = ['RANK','SACK_DST', 'INT_DST', 'FR_DST', 'FF_DST', 'DEF_TD_DST', 'SFTY_DST', 'SPC_TD_DST',
       'G_M', 'FPTS_M', 'FPTS/G_M', 'ROST_M'])

new_df_DST_2021['year'] = '2021'

new_df_DST_2021['position'] = 'DST'

In [311]:
stats_DST_2011_2021 = pd.concat([new_df_DST_2011, new_df_DST_2012, new_df_DST_2013, new_df_DST_2014, new_df_DST_2015, new_df_DST_2016, new_df_DST_2017, new_df_DST_2018, 
           new_df_DST_2019, new_df_DST_2020, new_df_DST_2021])

In [312]:
stats_DST_2011_2021.head()

                     PLAYER variable value  year position
0       Detroit Lions (DET)     RANK     1  2011      DST
1    Green Bay Packers (GB)     RANK     2  2011      DST
2       Chicago Bears (CHI)     RANK     3  2011      DST
3    Seattle Seahawks (SEA)     RANK     4  2011      DST
4  San Francisco 49ers (SF)     RANK     5  2011      DST

## unir las tablas

In [336]:
df_final_1 = pd.concat([stats_qb_2011_2021, stats_rb_2011_2021, stats_WR_2011_2021, stats_TE_2011_2021, stats_K_2011_2021, stats_DST_2011_2021])

In [337]:
df_final_1

                         PLAYER variable  value  year position
0            Aaron Rodgers (GB)     RANK      1  2011       QB
1               Drew Brees (FA)     RANK      2  2011       QB
2              Cam Newton (CAR)     RANK      3  2011       QB
3                Tom Brady (TB)     RANK      4  2011       QB
4        Matthew Stafford (LAR)     RANK      5  2011       QB
..                          ...      ...    ...   ...      ...
379  Jacksonville Jaguars (JAC)   ROST_M   7.0%  2021      DST
380  Los Angeles Chargers (LAC)   ROST_M  20.9%  2021      DST
381         Detroit Lions (DET)   ROST_M   2.8%  2021      DST
382       Atlanta Falcons (ATL)   ROST_M   6.0%  2021      DST
383         New York Jets (NYJ)   ROST_M   2.4%  2021      DST

[261500 rows x 5 columns]

In [338]:
df_final_1.to_csv('tabla_fantasy_2011_2021.csv')